version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes: # Map the local MongoDB data to the default location for MongoDB data in the container
      - $MONGODB_DATA:/data/db
      - $MONGODB_EXPORTS:/exports
